### ISSUE TITLE
Google Physical Layer not displaying

### ISSUE THREAD

**Issue by SteveMarvin** [jamiefolsom/Neatline-Archive#13]
While it has appeared previously, the Google Physical Layer no longer displays.

UPDATE: ~~It appears if more tan one base layer is active, but if Google Physical Layer is the only base layer enabled, it does not appear.~~

UPDATE #2: This is hard to pin down. Now I have both Google Streets and Physical coming up blank, when enabled together. 

![screen shot 2017-03-16 at 11 47 28 am](https://cloud.githubusercontent.com/assets/18423533/24005102/7615cb90-0a3e-11e7-8f8f-5a86f067edd5.png)

**Comment by jamiefolsom** [comment]
Shoot, might have broken it with that last deploy. Good catch. Re-deploying with dev assets included.

**Comment by SteveMarvin** [comment]
This now appears to be working properly. 👍

**Comment by jamiefolsom** [comment]
Closed by #413, which is now deployed to staging. Thx, @SteveMarvin!
