### ISSUE TITLE
Changing map zoom resets state of layer switcher

### ISSUE THREAD

**Issue by akstuhl** [jamiefolsom/Neatline-Archive#15]
Encountered while testing exhibit "arth4591 -> Establishment of Constantinople" on current master branch. If you toggle a map layer on/off and then zoom the map in or out, the toggle is undone and the layer switcher returned to the state in which it was loaded. This does not happen at http://arth4591.neatline-uva.org/neatline/show/establishment-of-constantinople

**Comment by jamiefolsom** [comment]
@akstuhl where are we on this one?

**Comment by akstuhl** [comment]
@jamiefolsom The issue is actually in https://github.com/scholarslab/nl-widget-Simile, and I've only been able to reproduce it in development environments. Continuing to investigate, but not a blocker for Neatline release.

**Comment by jamiefolsom** [comment]
OK great, I will remove it from the 2.5.2. milestone. Thanks, @akstuhl!

**Comment by jamiefolsom** [comment]
See https://github.com/scholarslab/nl-widget-Simile/issues/18
