### ISSUE TITLE
Test some existing exhibits against scholarslab/neatline#master with Omeka 2.5

### ISSUE THREAD

**Issue by jamiefolsom** [jamiefolsom/Neatline-Archive#8]
Hey @akstuhl,

Here's something for you to try out -- I've got a number of sample omeka installs, which it would be good to test against the latest version of both Omeka and Neatline (the current master, and/or the two open PR branches). Doesn't have to be on a live server, but just on localhost is fine. If that sounds like a good first task, let me know and I will send the tarballs along.

Thanks!

Jamie

**Comment by akstuhl** [comment]
Hey @jamiefolsom, sounds perfect! Up and running with a local install now, so I should be able to start swapping those in.
-Andy

**Comment by jamiefolsom** [comment]
👍

**Comment by jamiefolsom** [comment]
Done, thanks @akstuhl!
